import type { Metadata } from "next";
import "./globals.css";
import {PT_Serif} from "next/font/google";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-pt-serif',

});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ptSerif.variable} ${ptSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
